version: 2.1

workflows:
  main:
    jobs:
      - convert
      - deploy:
          requires:
            - convert
          filters:
            branches:
              only:
                - master
jobs:
  convert:
    working_directory: ~/hugo
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            git submodule sync
            git submodule update --init --recursive
            pip install jupyter
            pip install nb2hugo
            touch logs.txt
            python convert-to-md.py -d
      - persist_to_workspace:
          root: .
          paths: content
  deploy:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:N4bV+8n2dn6ThW0q+mgGUaqo2fmfhifNNH0y25SORtI annexdev02monzaw@gmail.com"
      - checkout
      - run: rm -rf public
      - run:
          name: Git Clone
          command: git clone --depth 1 https://github.com/monmonzaw/circle.github.io.git public
      - run:
          name: Hugo Build
          command: hugo --minify
      - run: cd public && touch CNAME && echo "$DOMAIN" > CNAME
      - run: cd public && pwd
      - run: cd public && git config --global user.email "${GIT_USER_EMAIL}"
      - run: cd public && git config --global user.name "${GIT_USER_NAME}"
      - run: cd public && git add -A
      - run: cd public && git commit -m "deploy from CI"
      - run: cd public && git push origin pages
